In [1]:
from sklearn import datasets
from sklearn import svm

# Load the digits dataset
digit = datasets.load_digits()

# Create an SVM classifier model (SC) and train it
s = svm.SVC(gamma=0.1, C=10)
s.fit(digit.data, digit.target)

# Define new samples for recognition
new_d = [digit.data[0], digit.data[1], digit.data[2]]

# Predict the labels for the new samples
res = s.predict(new_d)

# Print the results
print("Predicted Labels:", res)
print("Actual Labels:", digit.target[0], digit.target[1], digit.target[2])

# Use the training set as a test set for recognition and measure accuracy
res = s.predict(digit.data)

# Calculate accuracy
correct = [i for i in range(len(res)) if res[i] == digit.target[i]]
accuracy = len(correct) / len(res) * 100
print("Accuracy:", accuracy, "%")


Predicted Labels: [0 1 2]
Actual Labels: 0 1 2
Accuracy: 100.0 %


In [4]:
from sklearn import  datasets
from sklearn import  svm
from sklearn.model_selection import  train_test_split
import numpy as np
from sklearn.metrics import accuracy_score, confusion_matrix


digit = datasets.load_digits()
xtrain,xtest,ytrain,ytest = train_test_split(digit.data,digit.target,train_size=0.6)

In [5]:


# SVM 분류기 모델 생성 및 훈련
s = svm.SVC(gamma=0.001)
s.fit(xtrain, ytrain)

# 테스트 데이터에 대한 예측 수행
res = s.predict(xtest)

# 정확도 측정
accuracy = accuracy_score(ytest, res)
print("정확도:", accuracy)

# 혼동 행렬 계산
conf = confusion_matrix(ytest, res)
print("혼동 행렬:\n", conf)


정확도: 0.9860917941585535
혼동 행렬:
 [[67  0  0  0  0  0  0  0  0  0]
 [ 0 76  0  0  0  0  0  0  0  0]
 [ 0  0 67  0  0  0  0  0  0  0]
 [ 0  0  0 74  0  2  0  1  1  0]
 [ 0  0  0  0 75  0  0  0  1  1]
 [ 0  0  0  0  0 73  1  0  0  0]
 [ 0  0  0  0  0  0 74  0  0  0]
 [ 0  0  0  0  0  0  0 70  0  0]
 [ 0  2  0  0  0  0  0  0 73  0]
 [ 0  0  0  0  0  1  0  0  0 60]]


In [7]:
from sklearn.model_selection import train_test_split, cross_val_score

# 5-겹 교차 검증을 통한 정확도 계산
cv_scores = cross_val_score(s, digit.data, digit.target, cv=5, scoring='accuracy')


# 소수점 3자리까지 출력
print("평균 정확도:", "{:.3f}".format(cv_scores.mean()))
print("표준 편차:", "{:.3f}".format(cv_scores.std()))

평균 정확도: 0.972
표준 편차: 0.015
