2023/01/11
home alone coding
lets get init

#Soft Max Classification
more the three Class

**Data**

In [2]:
import torch
import torch.optim as optim


#data
x_train = [[1, 2], [2, 3], [3, 1], [4, 3], [5, 3], [6, 2]]
y_train = [[0], [0], [0], [1], [1], [1]]

x_train = torch.FloatTensor(x_train)
y_train = torch.FloatTensor(y_train)

#varification
print(x_train)
print(y_train)
print(x_train.shape)
print(y_train.shape)




tensor([[1., 2.],
        [2., 3.],
        [3., 1.],
        [4., 3.],
        [5., 3.],
        [6., 2.]])
tensor([[0.],
        [0.],
        [0.],
        [1.],
        [1.],
        [1.]])
torch.Size([6, 2])
torch.Size([6, 1])


**Leanring**

In [3]:


W = torch.ones((2,1),requires_grad=True)
b = torch.zeros(1, requires_grad=True)

#set optimizer
optimizer = optim.SGD([W,b] , lr = 1)

nb_epoch = 1000 #how many times are you going to enhance it

for epoch in range(nb_epoch + 1):
  #Cost calcualtion
  hypothesis = torch.sigmoid(x_train.matmul(W) + b)
  cost = -((y_train * torch.log(hypothesis)) + ((1-y_train)*torch.log(1 - hypothesis))).mean()
  optimizer.zero_grad()
  cost.backward()
  optimizer.step()
  W1 = W[0][0].item()
  W2 = W[1][0].item()
  
  
  #every 100 times
  if epoch % 100 == 0:
    print("Epoch : %4d/%d W1 : %f W2 : %f cost : %f"%(epoch,nb_epoch,W1,W2,cost))

Epoch :    0/1000 W1 : 0.020350 W2 : 0.022888 cost : 2.012506
Epoch :  100/1000 W1 : 1.575697 W2 : 0.409051 cost : 0.131138
Epoch :  200/1000 W1 : 1.974023 W2 : 0.744595 cost : 0.079377
Epoch :  300/1000 W1 : 2.258494 W2 : 0.939603 cost : 0.057256
Epoch :  400/1000 W1 : 2.478613 W2 : 1.077984 cost : 0.044908
Epoch :  500/1000 W1 : 2.658341 W2 : 1.185349 cost : 0.036998
Epoch :  600/1000 W1 : 2.810326 W2 : 1.273142 cost : 0.031483
Epoch :  700/1000 W1 : 2.942051 W2 : 1.347455 cost : 0.027413
Epoch :  800/1000 W1 : 3.058321 W2 : 1.411914 cost : 0.024282
Epoch :  900/1000 W1 : 3.162399 W2 : 1.468849 cost : 0.021798
Epoch : 1000/1000 W1 : 3.256615 W2 : 1.519849 cost : 0.019778


In [4]:
hypothesis = torch.sigmoid(x_train.matmul(W) + b)

prediction = hypothesis >= torch.FloatTensor([0.5])


correct_prediction = prediction.float() == y_train
print(correct_prediction[:5])

accuracy = correct_prediction.sum().item() / len(correct_prediction)
print('The model has an accuracy of {:2.2f}% for the training set.'.format(accuracy * 100))

tensor([[True],
        [True],
        [True],
        [True],
        [True]])
The model has an accuracy of 100.00% for the training set.


In [11]:
ManualInput = [[int(input()) for i in range(2)]]
print(ManualInput)
input_train = torch.FloatTensor(ManualInput);
hypothesis = torch.sigmoid(input_train.matmul(W) + b)
prediction = hypothesis >= torch.FloatTensor([0.5])
print(prediction)

[[2, 6]]
tensor([[True]])
