## Perceptron

solving XOR problem

21:47i

im tired
lets get init

## Not using NN
lets use basic knowlage to learn first

In [3]:
##Hardware
import torch
print("GPU Status ",end="")
print("Working Well") if torch.cuda.is_available() else print("Not good, Activating CPU calculation")
device = 'cuda' if torch.cuda.is_available() else print("cant use gpu//using cpu instead")
device = 'cuda' if torch.cuda.is_available() else 'cpu'
templist = [1,2,3]
templist = torch.FloatTensor(templist).to(device)
print("Cude torch working : ",end="")
print(templist.is_cuda)
print("current device no. : ",end="")
print(torch.cuda.current_device())
print("GPU device count : ",end="")
print(torch.cuda.device_count())
print("GPU name : ",end="")
print(torch.cuda.get_device_name(0))
print("device : ",device)


GPU Status Working Well
Cude torch working : True
current device no. : 0
GPU device count : 1
GPU name : NVIDIA GeForce GTX 1080
device :  cuda


In [4]:
import torch

X = torch.FloatTensor([[0,0], [0,1], [1,0],[1,1]]).to(device)
Y = torch.FloatTensor([[0],[1],[1],[0]]).to(device)

print(X)
print(Y)

tensor([[0., 0.],
        [0., 1.],
        [1., 0.],
        [1., 1.]], device='cuda:0')
tensor([[0.],
        [1.],
        [1.],
        [0.]], device='cuda:0')


In [5]:
W1 = torch.ones([2,1],requires_grad=True,device=device)  #Weights
W2 = torch.zeros([2,1],requires_grad=True,device=device)
W3 = torch.zeros([2,1],requires_grad=True,device=device)
b1 = torch.zeros(1,requires_grad=True,device=device)  #bias
b2 = torch.zeros(1,requires_grad=True,device=device)
b3 = torch.zeros(1,requires_grad=True,device=device)

In [6]:
Y1 = torch.sigmoid(X.matmul(W1) + b1)
print(Y1)
Y2 = torch.sigmoid(X.matmul(W2) + b2)
print(Y2)
Y12 = torch.cat([Y1,Y2],dim=1)
print(Y12.matmul(W3) + b3)
print(torch.sigmoid(Y12.matmul(W3) + b3))
hypothesis = torch.sigmoid(Y12.matmul(W3) + b3)

tensor([[0.5000],
        [0.7311],
        [0.7311],
        [0.8808]], device='cuda:0', grad_fn=<SigmoidBackward0>)
tensor([[0.5000],
        [0.5000],
        [0.5000],
        [0.5000]], device='cuda:0', grad_fn=<SigmoidBackward0>)
tensor([[0.],
        [0.],
        [0.],
        [0.]], device='cuda:0', grad_fn=<AddBackward0>)
tensor([[0.5000],
        [0.5000],
        [0.5000],
        [0.5000]], device='cuda:0', grad_fn=<SigmoidBackward0>)


In [11]:
import torch.optim as optim


optimizer = optim.SGD([W1,W2,W3,b1,b2,b3],lr=1)

nb_epoch = 10000

for epoch in range(nb_epoch + 1):
  
  #reset grad
  optimizer.zero_grad()
  #Calcualte Forward
  Y1 = torch.sigmoid(X.matmul(W1) + b1)
  Y2 = torch.sigmoid(X.matmul(W2) + b2)
  Y12 = torch.cat([Y1,Y2],dim=1)
  hypothesis = torch.sigmoid(Y12.matmul(W3) + b3)
  #Error calculation
  cost = -(Y * torch.log(hypothesis) + (1 - Y) * torch.log(1 - hypothesis)).mean()
  #Backwards calcuation
  cost.backward()
  #optim renew
  optimizer.step()
  if epoch % 1000 == 0:
    print("epoch : %d"%epoch,"cost : %.5f"%cost.item())
print(W1,b1)
print(W2,b2)
print(W3,b3)

print(hypothesis)


epoch : 0 cost : 0.00370
epoch : 1000 cost : 0.00265
epoch : 2000 cost : 0.00207
epoch : 3000 cost : 0.00169
epoch : 4000 cost : 0.00143
epoch : 5000 cost : 0.00124
epoch : 6000 cost : 0.00109
epoch : 7000 cost : 0.00098
epoch : 8000 cost : 0.00088
epoch : 9000 cost : 0.00081
epoch : 10000 cost : 0.00074
tensor([[8.0373],
        [8.0373]], device='cuda:0', requires_grad=True) tensor([-3.7277], device='cuda:0', requires_grad=True)
tensor([[6.2834],
        [6.2834]], device='cuda:0', requires_grad=True) tensor([-9.5951], device='cuda:0', requires_grad=True)
tensor([[ 15.4024],
        [-16.1719]], device='cuda:0', requires_grad=True) tensor([-7.3121], device='cuda:0', requires_grad=True)
tensor([[9.5636e-04],
        [9.9934e-01],
        [9.9934e-01],
        [6.7938e-04]], device='cuda:0', grad_fn=<SigmoidBackward0>)


In [12]:
with torch.no_grad(): #temporary grad = false

  preedicted = (hypothesis > 0.5).float()#float() changes true to 1 and false to 0

  accuracy = (preedicted == Y).float().mean()
  print("accuray : ",accuracy.item()*100,"%")

accuray :  100.0 %
