## Perceptron

solving XOR problem

21:47i

im tired
lets get init

## Not using NN
lets use basic knowlage to learn first

In [1]:
##Hardware
import torch
print("GPU Status ",end="")
print("Working Well") if torch.cuda.is_available() else print("Not good, Activating CPU calculation")
device = 'cuda' if torch.cuda.is_available() else print("cant use gpu//using cpu instead")
device = 'cuda' if torch.cuda.is_available() else 'cpu'
templist = [1,2,3]
templist = torch.FloatTensor(templist).to(device)
print("Cude torch working : ",end="")
print(templist.is_cuda)
print("current device no. : ",end="")
print(torch.cuda.current_device())
print("GPU device count : ",end="")
print(torch.cuda.device_count())
print("GPU name : ",end="")
print(torch.cuda.get_device_name(0))
print("device : ",device)


GPU Status Working Well
Cude torch working : True
current device no. : 0
GPU device count : 1
GPU name : NVIDIA GeForce GTX 1080
device :  cuda


In [38]:
import torch

X = torch.FloatTensor([[0,0], [0,1], [1,0],[1,1]]).to(device)
Y = torch.FloatTensor([[0],[1],[1],[0]]).to(device)

print(X)
print(Y)

tensor([[0., 0.],
        [0., 1.],
        [1., 0.],
        [1., 1.]], device='cuda:0')
tensor([[0.],
        [1.],
        [1.],
        [0.]], device='cuda:0')


In [40]:
W1 = torch.ones([2,1],requires_grad=True,device=device)  #Weights
W2 = torch.zeros([2,1],requires_grad=True,device=device)
W3 = torch.zeros([2,1],requires_grad=True,device=device)
b1 = torch.zeros(1,requires_grad=True,device=device)  #bias
b2 = torch.zeros(1,requires_grad=True,device=device)
b3 = torch.zeros(1,requires_grad=True,device=device)

In [41]:
Y1 = torch.sigmoid(X.matmul(W1) + b1)
print(Y1)
Y2 = torch.sigmoid(X.matmul(W2) + b2)
print(Y2)
Y12 = torch.cat([Y1,Y2],dim=1)
print(Y12.matmul(W3) + b3)
print(torch.sigmoid(Y12.matmul(W3) + b3))
hypothesis = torch.sigmoid(Y12.matmul(W3) + b3)

tensor([[0.5000],
        [0.7311],
        [0.7311],
        [0.8808]], device='cuda:0', grad_fn=<SigmoidBackward0>)
tensor([[0.5000],
        [0.5000],
        [0.5000],
        [0.5000]], device='cuda:0', grad_fn=<SigmoidBackward0>)
tensor([[0.],
        [0.],
        [0.],
        [0.]], device='cuda:0', grad_fn=<AddBackward0>)
tensor([[0.5000],
        [0.5000],
        [0.5000],
        [0.5000]], device='cuda:0', grad_fn=<SigmoidBackward0>)


In [51]:
import torch.optim as optim


optimizer = optim.SGD([W1,W2,W3,b1,b2,b3],lr=1)

nb_epoch = 1000

for epoch in range(nb_epoch + 1):
  
  #reset grad
  optimizer.zero_grad()
  #Calcualte Forward
  Y1 = torch.sigmoid(X.matmul(W1) + b1)
  Y2 = torch.sigmoid(X.matmul(W2) + b2)
  Y12 = torch.cat([Y1,Y2],dim=1)
  hypothesis = torch.sigmoid(Y12.matmul(W3) + b3)
  #Error calculation
  cost = -(Y * torch.log(hypothesis) + (1 - Y) * torch.log(1 - hypothesis)).mean()
  #Backwards calcuation
  cost.backward()
  #optim renew
  optimizer.step()
  if epoch & 100 == 0:
    print(epoch,cost.item())
print(W1,b1)
print(W2,b2)
print(W3,b3)

print(hypothesis)


0 0.0026510246098041534
1 0.002650262787938118
2 0.0026494855992496014
3 0.002648798283189535
8 0.0026450033765286207
9 0.002644286025315523
10 0.0026435242034494877
11 0.0026427621487528086
16 0.0026390566490590572
17 0.0026383092626929283
18 0.0026375921443104744
19 0.002636830322444439
24 0.0026331248227506876
25 0.0026323627680540085
26 0.0026316456496715546
27 0.0026308835949748755
128 0.002558167092502117
129 0.0025574946776032448
130 0.002556807594373822
131 0.002556060440838337
136 0.002552624326199293
137 0.0025518923066556454
138 0.002551205223426223
139 0.0025505328085273504
144 0.0025470517575740814
145 0.0025463197380304337
146 0.0025456473231315613
147 0.0025449602399021387
152 0.0025415089912712574
153 0.0025407769717276096
154 0.0025401345919817686
155 0.0025394472759217024
256 0.002471592742949724
257 0.002470920328050852
258 0.002470263047143817
259 0.002469620667397976
264 0.002466364298015833
265 0.0024657067842781544
266 0.0024651093408465385
267 0.0024644669611006

In [56]:
with torch.no_grad(): #temporary grad = false

  preedicted = (hypothesis > 0.5).float()#float() changes true to 1 and false to 0

  accuracy = (preedicted == Y).float().mean()
  print("accuray : ",accuracy.item()*100,"%")

accuray :  100.0 %
